[package]
name = "ipsc"
version = "0.1.0"
edition = "2021"
authors = ["maverick"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.34"
clap = { version = "4.4.7", features = ["derive"] }
